### PR TITLE
Nest 7

### PR DESCRIPTION
**Pull request by FrankZhang2046**
routing from all inventory to <ProductView /> is a go.

### CODE REVIEW

**Review by iskurbanov — APPROVED** [review]
Great success!!!!

**Comment by baikhuz** [comment]
tested. works. thanks Frank.

**Comment by baikhuz** [comment]
tested. works. thanks Frank.

**Comment by iskurbanov** [comment]
Test

**Review by baikhuz — APPROVED** [review]
tested. works. thanks Frank.

**Pull request merged**
